### ISSUE TITLE
Solidity looks quite boring

### ISSUE THREAD

**Issue by cserb** [akai54/2077.nvim#1]
![Screenshot 2023-01-12 at 13 19 46](https://user-images.githubusercontent.com/1147993/212065598-d0ef7860-ed3a-49a5-a676-587ee98f8f5c.png)
Something wrong with treesitter here?

**Comment by akai54** [comment]
Hi!
thank you for opening this issue, sadly I'll not be able to solve it right now as I have a planned a 2.0 version of this color scheme, completely rewritten, that should solve this and other issues as well.
